### PR TITLE
Add Cookie methods that can clear same_site/max_age/path/domain

### PR DESCRIPTION
**Pull request by erickt**
This allows us to remove the values for Option types.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Should we instead take in a `T: Into<Option<_>>` in the existing `set_` functions?

**Comment by erickt** [comment]
Sure, that'd work too. I'll update my PR.

**Comment by erickt** [comment]
@SergioBenitez: I don't think this will quite work. For example:

```rust
    pub fn set_path<T, P>(&mut self, path: T)
        where T: Into<Option<P>>,
              P: Into<Cow<'static, str>>,
    {
        self.path = path.into().map(|path| {
            CookieStr::Concrete(path.into())
        });
    }
```

Rust gets rather confused when you try to do `cookie.set_path(None);`. I still haven't yet figured out what type annotation I need to specify in order to get it to work.

What if we just change the method to take an `Option<_>` type?

**Comment by Boscop** [comment]
Any update on this? :)
We need a way to not set SameSite at all.

**Comment by SergioBenitez** [comment]
@Boscop I've added the `SameSite::None` variant to handle this case.

**Pull request closed without merging**
