### PR TITLE
add plain cookie wrappers

### PR DESCRIPTION
**Pull request by robjtede**
Further to comment discussions on https://github.com/actix/actix-web/pull/1558.

Will fill in remaining docs if this approach is acceptable.

### CODE REVIEW

**Comment by rsnakard-r7** [comment]
Why not use `Cookie::name_value()`?

**Comment by robjtede** [comment]
That could help with the plain case but not the plain_encoded case.

**Comment by robjtede** [comment]
Interested to hear your view on what this API should look like @SergioBenitez given you've seen the use-case we're trying to achieve.

**Comment by SergioBenitez** [comment]
@robjtede Apologies for the delay. I've revamped the way configurable displaying works in https://github.com/SergioBenitez/cookie-rs/commit/7efcdd83b8ded99ea86a9d00ed72cd211323949b. You can do:

```rust
cookie.encoded(); // encode name/value, display everything, as before
cookie.stripped(); // display only name/value, unencoded
cookie.stripped().encoded(); // display encoded name/value
cookie.encoded().stripped(); // display encoded name/value
```

This will ship in the next major release.

**Pull request closed without merging**
